version: '3.8'

services:
  db:
    build: ./db
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - api
    volumes:
      - db:/var/lib/mysql
  api:
    build: ./api
    links:
      - db
    depends_on:
      - db
    restart: on-failure
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=5
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    networks:
      - api
    volumes:
      - ./api:/api

volumes: 
  db:

networks:
  api: