version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    networks:
      - app-tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
    networks:
      - app-tier
